import mongoose from "mongoose";

const Schema = mongoose.Schema;

const DiscountSchema = new Schema({
  shop: String,
  metaId: [String],
  blockTitle: String,
  offerName: String,
  product: String,
  productArray: [String],
  productId: [String],
  discountTarget: String,
  collectionId: [String],
  productCollection: String,
  productCollectionArray: [String],
  template: String,
  quantity: [String],
  title: [String],
  subtitle: [String],
  price: [String],
  discount: [String],
  label: [String],
  defaultSelected: String,
  labelSelected: [Boolean],
  subtitleSelected: [Boolean],
  titleColor: String,
  discountColor: String,
  textColor: String,
  labelColor: String,
  blockTitleColor: String,
  borderColor: String,
  backgroundColor: String,
  footerColor: String,
  titleSizeTypo: String,
  titleStyleTypo: String,
  discountSizeTypo: String,
  discountStyleTypo: String,
  textSizeTypo: String,
  textStyleTypo: String,
  labelSizeTypo: String,
  labelStyleTypo: String,
  blockTitleSizeTypo: String,
  blockTitleStyleTypo: String,
  footerSizeTypo: String,
  hideHeaderFooterLines: { type: Boolean, default: false },
  footerStyleTypo: String,
  borderWidth: String,
  borderRadius: String,
  includeVarient: Boolean,
  compareToPrice: Boolean,
  enableCustomCompareAtPrice: { type: Boolean, default: false },
  customCompareAtPrice: { type: String, default: "0" },
  showTotalPrice: Boolean,
  showPriceByEach: Boolean,
  footerText: String,
  discountGid: String,
  discountTitles: String,
  productUrl: String,
  status: String,
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

export default mongoose.model("Discount", DiscountSchema);
